apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: peakservices.services.peak-oss.net
spec:
  group: services.peak-oss.net
  names:
    kind: PeakService
    listKind: PeakServiceList
    plural: peakservices
    singular: peakservice
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
