apiVersion: v1
kind: ServiceAccount
metadata:
  name: peak
  labels:
    app: peak
---
apiVersion: v1
groupNames: null
kind: RoleBinding
metadata:
  name: peak
  labels:
    app: peak
roleRef:
  name: admin
subjects:
- kind: ServiceAccount
  name: peak
