apiVersion: apps/v1
kind: Deployment
metadata:
  name: peak-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: peak-operator
  template:
    metadata:
      labels:
        name: peak-operator
    spec:
      serviceAccountName: peak-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: "quay.io/peak/peak-operator:v0.1.7"
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          image: "quay.io/peak/peak-operator:v0.1.7"
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "peak-operator"
      volumes:
        - name: runner
          emptyDir: {}
