apiVersion: apps/v1
kind: Deployment
metadata:
  name: peak-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: peak-operator
  template:
    metadata:
      labels:
        name: peak-operator
    spec:
      serviceAccountName: peak-operator
      containers:
        - name: peak-operator
          image: "quay.io/peak/peak-operator:v0.0.5"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "peak-operator"
