apiVersion: apps/v1
kind: Deployment
metadata:
  name: peak-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: peak-operator
  template:
    metadata:
      labels:
        name: peak-operator
    spec:
      serviceAccountName: peak-operator
      containers:
        - name: peak-operator
          # Replace this with the built image name
          image: "{{ REPLACE_IMAGE }}"
          imagePullPolicy: "{{ pull_policy|default('Always') }}"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "peak-operator"
